server:
  port: 8080
  address: 0.0.0.0
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_NAME:rve}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:lhs0324*}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ihansaem60@gmail.com
    password: fkch gzfh qdcs uhuq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY:sdkfkjshdfjkahsdkjfhkjasdhfjkahfd}
  access-exp: ${JWT_ACCESS_EXP:604800000}
  refresh-exp: ${JWT_REFRESH_EXP:604800000}
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:lhs0324*}
